// File generated by FlutterFire CLI and shared with the mobile app.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgX8-ILulZ1HAY8UTeivVv_HDXuJyi2uM',
    appId: '1:420672794830:web:2013ddfa4a3fdc54aca09f',
    messagingSenderId: '420672794830',
    projectId: 'piproject-92e05',
    authDomain: 'project-pi-92e05.firebaseapp.com',
    storageBucket: 'project-pi-92e05.firebasestorage.app',
    measurementId: 'G-XVG25YCF0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKCq6gq0nmA6o8xaQq-GZbx9DMcA5_lH0',
    appId: '1:272451779584:android:f0573749035c6a2b59ace5',
    messagingSenderId: '272451779584',
    projectId: 'piproject-92e05',
    storageBucket: 'piproject-92e05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6mDCT5hOsMGBzSj_sDz_7XPEYbQNuh8E',
    appId: '1:420672794830:ios:779d4476caf96c86aca09f',
    messagingSenderId: '420672794830',
    projectId: 'project-pi-63837',
    storageBucket: 'project-pi-63837.firebasestorage.app',
    iosBundleId: 'com.example.constructionflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6mDCT5hOsMGBzSj_sDz_7XPEYbQNuh8E',
    appId: '1:420672794830:ios:779d4476caf96c86aca09f',
    messagingSenderId: '420672794830',
    projectId: 'project-pi-63837',
    storageBucket: 'project-pi-63837.firebasestorage.app',
    iosBundleId: 'com.example.constructionflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgX8-ILulZ1HAY8UTeivVv_HDXuJyi2uM',
    appId: '1:420672794830:web:3926b81d7ac4c72daca09f',
    messagingSenderId: '420672794830',
    projectId: 'piproject-92e05',
    authDomain: 'piproject-92e05.firebaseapp.com',
    storageBucket: 'piproject-92e05.firebasestorage.app',
    measurementId: 'G-YBJSCBEDYY',
  );
}
